/*
 * DailyCost Localization
 * ----------------------
 * Japanese
 *
 */

(function(app) {
	"use strict";

	app.addLanguage("ja", {

		preference: {
			"currency": "JPY".split("_")
		},

		string: {
			"weekdays": "日曜日_月曜日_火曜日_水曜日_木曜日_金曜日_土曜日".split("_"),
			"weekdaysShort": "日曜_月曜_火曜_水曜_木曜_金曜_土曜".split("_"),
			"pullText": "新規...|新規支...|新規支出...|新規支出を...|新規支出を記...|新規支出を記録...|新規支出を記録!".split("|"),
			"formatMetaDate": 'MM[<span>]DD[</span>] [<span class="day">]ddd[</span>]',

			"settings": "設定",
			"preferences": "嗜好",
			"categories": "支出種類",
			"wallpaper": "壁紙",
			"general": "一般",
			"accountSettings": "アカウント",
			"account": "私のアカウント",
			"sharing": "シェアリング",
			"currency": "貨幣",
			"security": "機密保護",
			"feedback": "饋還",
			"about": "について",
			"tipsAndTricks": "使用攻略",
			"preview": "内見",
			"done": "完成",
			"submit": "提出",
			"restore": "戻す",
			"default": "既定",
			"weekStart": "週に始まる",

			"data": "資料",
			"dataExportCSV": "メールのエクスポートExcel (CSV)", // "エクスポートCSV"
			"dataExportEmailSubject": "DailyCost資料のバックアップ",
			"dataExportEmailBody": "Keep it simple and elegant.",

			"date": "日付",
			"sum": "額",
			"category": "種類",

			"favoriteCurrencies": "一般の貨幣",
			"allCurrencies": "全部の貨幣",

			"emptyCatlist": "ウープス ここには支出もありません",

			"feedbackEmailSubject": "DailyCost饋還",

			"rollDays": "日",
			"rollTotal": "支出",
			"rollTotalSum": "総計",

			"note": "付記",
			"createdOn": "時間",

			"ratingsTitle": "評価DailyCost",
			"ratingsDescriptions": "あなたはDailyCostを使用して楽しむ場合は、それを評価する瞬間を取っていただけませんか？それは数分以上かかることはありません。ご支援いただきありがとうございます！",
			"ratingsButtons": "評価し,後ほど"
		},

		category: {
			"default":        "一般",
			"food":           "食物",
			"food-breakfast": "朝食",
			"food-lunch":     "昼食",
			"food-dinner":    "夕食",
			"drinks":         "飲料",
			"groceries":      "乾物",
			"shopping":       "買物",

			"personal":       "個人",
			"entertain":      "遊び",
			"movies":         "映画",
			"social":         "社交",
			"transport":      "輸送",

			"appstore":       "App Store",
			"mobile":         "電話",
			"computer":       "計算機",
			"gifts":          "寄贈",
			"housing":        "住宅",

			"travel":         "旅行",
			"tickets":        "券",
			"books":          "図書",
			"medical":        "医療",
			"transfer":       '為替'
		},

		currency: {
			"AED": "UAEディルハム",
				"AFN": "アフガニスタン・アフガニ",
				"ALL": "アルバニア・レク",
				"AMD": "アルメニア ドラム",
				"ANG": "アンティル ギルダー",
				"AOA": "アンゴラ クワンザ",
			"ARS": "アルゼンチン・ペソ",
			"AUD": "オーストラリア・ドル",
				"AWG": "アルバ フローリン",
				"AZN": "Azerbaijani New Manat",
				"BAM": "Bosnian Convertible Marka",
				"BBD": "バルバドス ドル",
				"BDT": "バングラデシュ タカ",
				"BGN": "ブルガリア レフ",
				"BHD": "バーレーン ディナール",
				"BIF": "ブルンジ フラン",
				"BMD": "バミューダ ドル",
				"BND": "ブルネイ ドル",
				"BOB": "ボリビア ボリビアーノ",
			"BRL": "ブラジル・レアル",
				"BSD": "バハマ ドル",
				"BTN": "ブータン ニュルタム",
				"BWP": "ボツワナ プラ",
				"BYR": "ベラルーシ ルーブル",
				"BZD": "ベリーズ ドル",
			"CAD": "カナダ・ドル",
				"CDF": "コンゴ フラン",
			"CHF": "スイス・フラン",
			"CLP": "チリ・ペソ",
			"CNY": "中国元",
				"COP": "コロンビア ペソ",
				"CRC": "コスタリカ コロン",
				"CUC": "キューバ ペソ",
				"CUP": "キューバ ペソ",
				"CVE": "カーボベルデ エスクード",
			"CZK": "チェコ・コルナ",
				"DJF": "ジブチ フラン",
			"DKK": "デンマーク・クローネ",
				"DOP": "ドミニカ ペソ",
				"DZD": "アルジェリア ディナール",
			"EGP": "エジプト・ポンド",
				"ERN": "エリトリア ナクファ",
				"ETB": "エチオピア ブル",
			"EUR": "欧州ユーロ",
				"FJD": "フィジー ドル",
				"FKP": "フォークランド諸島 ポンド",
			"GBP": "イギリス・ポンド",
				"GEL": "グルジア ラリ",
				"GGP": "ガーンジー ポンド",
				"GHS": "Ghanaian Cedi",
				"GIP": "ジブラルタル ポンド",
				"GMD": "ガンビア ダラシ",
				"GNF": "ギニア フラン",
				"GTQ": "グアテマラ ケツァル",
				"GYD": "ガイアナ ドル",
			"HKD": "香港ドル",
				"HNL": "ホンジュラス レンピラ",
				"HRK": "クロアチア クーナ",
				"HTG": "ハイチ グールド",
			"HUF": "ハンガリー・フォリント",
			"IDR": "インドネシア・ルピア",
			"ILS": "イスラエル・新シェケル",
				"IMP": "Isle of Man Pound",
			"INR": "インド・ルピー",
				"IQD": "イラク ディナール",
				"IRR": "イラン リアル",
				"ISK": "アイスランド クローナ",
				"JEP": "Jersey Pound",
				"JMD": "ジャマイカ ドル",
				"JOD": "ヨルダン ディナール",
			"JPY": "日本円",
				"KES": "ケニア シリング",
				"KGS": "キルギス ソム",
				"KHR": "カンボジア リエル",
				"KMF": "コモロ フラン",
				"KPW": "朝鮮ウォン",
			"KRW": "韓国ウォン",
				"KWD": "クウェート ディナール",
				"KYD": "ケイマン諸島 ドル",
				"KZT": "カザフスタン テンゲ",
			"LAK": "ラオス・キープ",
				"LBP": "レバノン ポンド",
				"LKR": "スリランカ ルピー",
				"LRD": "リベリア ドル",
				"LSL": "レソト ロチ",
				"LTL": "リトアニア リタス",
				"LVL": "ラトビア ラッツ",
				"LYD": "リビア ディナール",
				"MAD": "モロッコ ディルハム",
				"MDL": "モルドバ レウ",
				"MGA": "マダガスカル アリアリ",
				"MKD": "マケドニア ディナール",
				"MMK": "Burmese Kyat",
			"MNT": "モンゴル国・トゥグルグ",
				"MOP": "マカオ パタカ",
				"MRO": "モーリタニア ウギア",
				"MUR": "モーリシャス ルピー",
				"MVR": "モルディブ ルフィヤ",
				"MWK": "マラウイ クワチャ",
			"MXN": "メキシコ・ペソ",
			"MYR": "マレーシア・リンギット",
				"MZN": "Mozambican Metical",
				"NAD": "ナミビア ドル",
			"NGN": "ナイジェリア・ナイラ",
				"NIO": "コルドバ オロ",
			"NOK": "ノルウェー・クローネ",
				"NPR": "ネパール ルピー",
			"NZD": "ニュージーランド・ドル",
				"OMR": "オマーン リヤル",
				"PAB": "パナマ バルボア",
				"PEN": "ペルー ソル",
				"PGK": "パプアニューギニア キナ",
			"PHP": "フィリピン・ペソ",
				"PKR": "パキスタン ルピー",
			"PLN": "ポーランド・ズウォティ",
				"PYG": "パラグアイ グァラニ",
				"QAR": "カタール リヤル",
				"RON": "ルーマニア レウ",
				"RSD": "セルビア ディナール",
			"RUB": "ロシア・ルーブル",
				"RWF": "ルワンダ フラン",
			"SAR": "サウジアラビア・リヤル",
				"SBD": "ソロモン諸島 ドル",
				"SCR": "セーシェル ルピー",
				"SDG": "スーダン ポンド",
			"SEK": "スウェーデン・クローナ",
			"SGD": "シンガポール・ドル",
				"SHP": "セントヘレナ ポンド",
				"SLL": "シエラレオネ レオン",
				"SOS": "ソマリア シリング",
				"SPL": "Seborgan Luigino",
				"SRD": "スリナム ドル",
				"STD": "Sao Tomean Dobra",
				"SVC": "Salvadoran Colon",
				"SYP": "シリア ポンド",
				"SZL": "スワジランド リランゲニ",
			"THB": "タイ・バーツ",
				"TJS": "タジキスタン ソモニ",
				"TMT": "Turkmenistani Manat",
				"TND": "チュニジア ディナール",
				"TOP": "Tongan Pa'anga",
			"TRY": "トルコ・リラ",
				"TTD": "トリニダード・トバゴ ドル",
				"TVD": "Tuvaluan Dollar",
			"TWD": "新台湾ドル",
				"TZS": "タンザニア シリング",
			"UAH": "ウクライナ フリヴニャ",
				"UGX": "ウガンダ シリング",
			"USD": "アメリカ・ドル",
				"UYU": "ウルグアイ ペソ",
				"UZS": "ウズベキスタン・スム",
				"VEF": "ベネズエラ ボリバル・フエルテ",
			"VND": "ベトナム・ドン",
				"VUV": "バヌアツ バツ",
				"WST": "サモア タラ",
				"XAF": "CFA フラン",
				"XAG": "Silver Ounce",
				"XAU": "Gold Ounce",
				"XCD": "東カリブ ドル",
				"XDR": "IMF Special Drawing Rights",
				"XOF": "CFA フラン",
				"XPD": "Palladium Ounce",
				"XPF": "CFP フラン",
				"XPT": "Platinum Ounce",
				"YER": "Yemeni Rial",
			"ZAR": "南アフリカ・ランド",
				"ZMW": "Zambian Kwacha",
				"ZWD": "Zimbabwean Dollar"
		}

	});

}(DAILYCOST || {}));
