/*
 * DailyCost Localization
 * ----------------------
 * Chinese Simplified (PRC)
 *
 */

(function(app) {
	"use strict";

	app.addLanguage("zh-cn", {

		preference: {
			"currency": "CNY".split("_")
		},

		string: {
			"weekdays": "周日_周一_周二_周三_周四_周五_周六".split("_"),
			"weekdaysShort": "周日_周一_周二_周三_周四_周五_周六".split("_"),
			"pullText": "新增...|新增一...|新增一条...|新增一条开...|新增一条开销...|新增一条开销!".split("|"),
			// "formatMetaDate": 'MM[<span>]DD[</span>] [<span class="day">]ddd[</span>]',
			"formatMetaDate": '[<strong>]MM.DD[</strong>]',
			"formatSameMonthWeekScope1": '[<strong>]MM.DD[</strong>]',
			"formatSameMonthWeekScope2": '[<strong>]DD[</strong>]',
/*
			"formatMetaDate": '[<strong>]M[</strong>月][<strong>]DD[</strong>日]',
			"formatSameMonthWeekScope1": '[<strong>]M[</strong>月][<strong>]DD[</strong>日]',
			"formatSameMonthWeekScope2": '[<strong>]DD[</strong>日]',
*/
/*
			"formatMetaDate": 'M[月]DD[日]',
			"formatSameMonthWeekScope1": 'M[月]DD[日]',
			"formatSameMonthWeekScope2": 'DD[日]',
*/
/*
			"formatMetaDate": '[<strong>]M[月]DD[日</strong>]',
			"formatSameMonthWeekScope1": '[<strong>]M[月]DD[日</strong>]',
			"formatSameMonthWeekScope2": '[<strong>]DD[日</strong>]',
*/

			"settings": "设置",
			"preferences": "使用偏好",
			"categories": "开销类别",
			"wallpaper": "壁纸",
			"general": "通用",
			"accountSettings": "帐号",
			"account": "我的 DailyCost 帐号",
			"sharing": "分享",
			"currency": "货币",
			"security": "安全",
			"feedback": "建议与反馈",
			"about": "关于",
			"tipsAndTricks": "使用秘籍",
			"preview": "预览",
			"done": "完成",
			"submit": "提交",
			"restore": "还原",
			"default": "默认",
			"weekStart": "每周开始于",

			"data": "数据",
			"dataExportCSV": "邮件导出Excel文件(CSV)", // "通过Email导出CSV"
			"dataExportEmailSubject": "DailyCost数据备份",
			"dataExportEmailBody": "Keep it simple and elegant.",

			"date": "日期",
			"sum": "金额",
			"category": "类别",

			"entry": "记录",
			"cost": "开销",
			"earn": "收入",
			"balance": "总额",

			"favoriteCurrencies": "常用货币",
			"allCurrencies": "全部货币",

			"emptyCatlist": "亲，这儿还没有任何记录哦",

			"feedbackEmailSubject": "DailyCost反馈",

			"rollDays": "天数",
			"rollTotal": "开销",
			"rollTotalSum": "总金额",

			"note": "备注",
			"createdOn": "记录于",

			"ratingsTitle": "给DailyCost评分",
			"ratingsDescriptions": "如果您喜欢DailyCost，现在就花点时间写个评论吧！您的意见和建议会让它变得更出色。",
			"ratingsButtons": "去评分,下次吧"
		},

		category: {
			"default":        "一般",
			"food":           "餐饮",
			"food-breakfast": "早餐",
			"food-lunch":     "午餐",
			"food-dinner":    "晚餐",
			"drinks":         "饮料",
			"groceries":      "水果零食",
			"shopping":       "购物",

			"personal":       "个人",
			"entertain":      "娱乐",
			"movies":         "电影",
			"social":         "社交",
			"transport":      "交通",

			"appstore":       "App Store",
			"mobile":         "手机通讯",
			"computer":       "电脑",
			"gifts":          "礼品",
			"housing":        "居家",

			"travel":         "旅行",
			"tickets":        "门票",
			"books":          "书籍",
			"medical":        "医疗",
			"transfer":       "转帐"
		},

		currency: {
			"AED": "阿联酋迪拉姆",
				"AFN": "阿富汗阿富汗尼",
				"ALL": "阿尔巴尼亚勒克",
				"AMD": "亚美尼亚德拉姆",
				"ANG": "荷兰盾",
				"AOA": "安哥拉宽扎",
			"ARS": "阿根廷比索",
			"AUD": "澳元",
				"AWG": "Aruban or Dutch Guilder",
				"AZN": "阿塞拜疆新马纳特",
				"BAM": "波斯尼亚兑换马尔卡",
				"BBD": "巴巴多斯元",
				"BDT": "孟加拉塔卡",
				"BGN": "保加利亚利瓦",
				"BHD": "巴林第纳尔",
				"BIF": "布隆迪法郎",
				"BMD": "百慕大元",
				"BND": "文莱元",
				"BOB": "Bolivian Boliviano",
			"BRL": "巴西雷亚尔",
				"BSD": "Bahamian Dollar",
				"BTN": "Bhutanese Ngultrum",
				"BWP": "Botswana Pula",
				"BYR": "Belarusian Ruble",
				"BZD": "Belizean Dollar",
			"CAD": "加拿大元",
				"CDF": "Congolese Franc",
			"CHF": "瑞士法郎",
			"CLP": "智利比索",
			"CNY": "人民币",
			"COP": "哥伦比亚比索",
			"CRC": "哥斯达黎加科隆",
				"CUC": "Cuban Convertible Peso",
				"CUP": "Cuban Peso",
				"CVE": "Cape Verdean Escudo",
			"CZK": "捷克克郎",
				"DJF": "Djiboutian Franc",
			"DKK": "丹麦克朗",
				"DOP": "Dominican Peso",
				"DZD": "Algerian Dinar",
			"EGP": "埃及镑",
				"ERN": "Eritrean Nakfa",
				"ETB": "Ethiopian Birr",
			"EUR": "欧元",
				"FJD": "Fijian Dollar",
				"FKP": "Falkland Island Pound",
			"GBP": "英镑",
				"GEL": "Georgian Lari",
				"GGP": "Guernsey Pound",
				"GHS": "Ghanaian Cedi",
				"GIP": "Gibraltar Pound",
				"GMD": "Gambian Dalasi",
				"GNF": "Guinean Franc",
				"GTQ": "Guatemalan Quetzal",
				"GYD": "Guyanese Dollar",
			"HKD": "港元",
				"HNL": "Honduran Lempira",
				"HRK": "Croatian Kuna",
				"HTG": "Haitian Gourde",
			"HUF": "匈牙利福林",
			"IDR": "印尼盾",
			"ILS": "以色列新谢克尔",
				"IMP": "Isle of Man Pound",
			"INR": "印度卢比",
				"IQD": "Iraqi Dinar",
				"IRR": "Iranian Rial",
				"ISK": "Icelandic Krona",
				"JEP": "Jersey Pound",
				"JMD": "Jamaican Dollar",
				"JOD": "Jordanian Dinar",
			"JPY": "日元",
				"KES": "Kenyan Shilling",
				"KGS": "Kyrgyzstani Som",
				"KHR": "柬埔寨瑞尔",
				"KMF": "Comoran Franc",
				"KPW": "North Korean Won",
			"KRW": "韩元",
				"KWD": "Kuwaiti Dinar",
				"KYD": "Caymanian Dollar",
				"KZT": "Kazakhstani Tenge",
			"LAK": "老挝基普",
				"LBP": "Lebanese Pound",
				"LKR": "Sri Lankan Rupee",
				"LRD": "Liberian Dollar",
				"LSL": "Basotho Loti",
				"LTL": "Lithuanian Litas",
				"LVL": "Latvian Lat",
				"LYD": "Libyan Dinar",
				"MAD": "Moroccan Dirham",
				"MDL": "Moldovan Leu",
				"MGA": "Malagasy Ariary",
				"MKD": "Macedonian Denar",
				"MMK": "Burmese Kyat",
			"MNT": "蒙古图格里克",
				"MOP": "Macau Pataca",
				"MRO": "Mauritanian Ouguiya",
				"MUR": "Mauritian Rupee",
				"MVR": "Maldivian Rufiyaa",
				"MWK": "Malawian Kwacha",
			"MXN": "墨西哥比索",
			"MYR": "马来西亚林吉特",
				"MZN": "Mozambican Metical",
				"NAD": "Namibian Dollar",
			"NGN": "尼日利亚奈拉",
				"NIO": "Nicaraguan Cordoba",
			"NOK": "挪威克朗",
				"NPR": "Nepalese Rupee",
			"NZD": "新西兰元",
				"OMR": "Omani Rial",
				"PAB": "Panamanian Balboa",
				"PEN": "Peruvian Nuevo Sol",
				"PGK": "Papua New Guinean Kina",
			"PHP": "菲律宾比索",
				"PKR": "Pakistani Rupee",
			"PLN": "波兰兹罗提",
				"PYG": "Paraguayan Guarani",
				"QAR": "Qatari Riyal",
			"RON": "罗马尼亚新列伊",
				"RSD": "Serbian Dinar",
			"RUB": "俄罗斯卢布",
				"RWF": "Rwandan Franc",
			"SAR": "沙特里亚尔",
				"SBD": "Solomon Islander Dollar",
				"SCR": "Seychellois Rupee",
				"SDG": "Sudanese Pound",
			"SEK": "瑞典克朗",
			"SGD": "新加坡元",
				"SHP": "Saint Helenian Pound",
				"SLL": "Sierra Leonean Leone",
				"SOS": "Somali Shilling",
				"SPL": "Seborgan Luigino",
				"SRD": "Surinamese Dollar",
				"STD": "Sao Tomean Dobra",
				"SVC": "Salvadoran Colon",
				"SYP": "Syrian Pound",
				"SZL": "Swazi Lilangeni",
			"THB": "泰铢",
				"TJS": "Tajikistani Somoni",
				"TMT": "Turkmenistani Manat",
				"TND": "Tunisian Dinar",
				"TOP": "Tongan Pa'anga",
			"TRY": "土耳其里拉",
				"TTD": "Trinidadian Dollar",
				"TVD": "Tuvaluan Dollar",
			"TWD": "新台币",
				"TZS": "Tanzanian Shilling",
			"UAH": "乌克兰格里夫纳",
				"UGX": "Ugandan Shilling",
			"USD": "美元",
			"UYU": "乌拉圭比索",
				"UZS": "Uzbekistani Som",
				"VEF": "Venezuelan Bolivar",
			"VND": "越南盾",
				"VUV": "Ni-Vanuatu Vatu",
				"WST": "Samoan Tala",
				"XAF": "Central African CFA Franc BEAC",
				"XAG": "Silver Ounce",
				"XAU": "Gold Ounce",
				"XCD": "East Caribbean Dollar",
				"XDR": "IMF Special Drawing Rights",
				"XOF": "CFA Franc",
				"XPD": "Palladium Ounce",
				"XPF": "CFP Franc",
				"XPT": "Platinum Ounce",
				"YER": "Yemeni Rial",
			"ZAR": "南非兰特",
				"ZMW": "Zambian Kwacha",
				"ZWD": "Zimbabwean Dollar"
		}

	});

}(DAILYCOST || {}));
